name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Remove pptx files
        run: |
          git rm -r --cached deliverables/*.pptx --ignore-unmatch
          git commit -m "exclude pptx from HF push" --allow-empty
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.BANTRLY }}
        run: git push https://aankitdas:$HF_TOKEN@huggingface.co/spaces/aankitdas/bantrly-lesson-generator main --force